### ISSUE TITLE
Feature Request: Comment Caching

### ISSUE THREAD

**Issue by LePatBlack** [z0ccc/voat-extension#18]
I'm not well-versed on the correct terminology to describe this feature, but it'd be great for both the user and Reddit's servers if comments were cached for at least a few minutes once loaded. If I accidentally click away, clicking back to view the comments causes another request to pull that data, unless it is already cached and it just takes a minute to populate locally regardless.

Love this software. Thank you!

**Comment by z0ccc** [comment]
Implemented.
