### ISSUE TITLE
Feature Request: Option to hide posts with no comments or a way to ignore certain subreddits

### ISSUE THREAD

**Issue by brianbuie** [z0ccc/voat-extension#30]
Thanks for this extension, it's great!

It would be awesome if there was a setting for hiding reddit posts that don't have any comments, since there isn't much value in seeing them under youtube videos. 

There are a few subreddits that show up frequently without comments ([r/throwaway_the_videos](https://www.reddit.com/r/throwaway_the_videos/), [r/mealtimevideos](https://www.reddit.com/r/mealtimevideos/)), so providing a way to ignore certain subreddits could also be helpful.

**Comment by z0ccc** [comment]
Implemented.
