### ISSUE TITLE
Voat CSS is messing with Youtube styles

### ISSUE THREAD

**Issue by mattaningram** [z0ccc/voat-extension#34]
I really like this extension but it needs to be more careful with its CSS. Your classnames are too generic and not scoped to just where they are needed so things like `.message` are causing the Youtube notification messages to be center aligned incorrectly.

In general when an extension injects CSS into an existing site you have to be very careful to very specifically name your classes or at least nest them one level in a uniquely named parent class so they don't impact existing styles on the page.

<img width="511" alt="image" src="https://user-images.githubusercontent.com/955092/225086935-e52f0eac-e4e2-4ff6-9f38-dae3810f7a6a.png">

<img width="385" alt="image" src="https://user-images.githubusercontent.com/955092/225087119-abe03dc1-1621-4902-ba8e-b12624cc0352.png">

**Comment by wbs-perso** [comment]
I can confirm that after some extension isolation and troubleshooting I experience the same issue only when the Voat extension is active.

**Comment by HatScripts** [comment]
I'm also experiencing this bug. It's not the end of the world, but it is kind of annoying. @mattaningram said it well, you need to reduce the scope of your CSS selectors. Rather than `.message` it should be `#redComments .message`.
