### ISSUE TITLE
Compatibility with other extensions

### ISSUE THREAD

**Issue by LaundryHamper** [z0ccc/voat-extension#38]
Voat is superb, but I would love to be able to use it with this extension, which puts the comment section beside the video - https://github.com/tberghuis/watch-and-read-comments-for-youtube

Alternatively, perhaps an option for the extension button to open the window as a sidebar app could work as a solution that's less likely to require maintenance.

**Comment by z0ccc** [comment]
Support for the side panel api has been added to chrome.
