### ISSUE TITLE
Will the new Reddit API rules affect this extension?

### ISSUE THREAD

**Issue by TheLime1** [z0ccc/voat-extension#39]

**Comment by ixney** [comment]
It's not using OAuth so it should be 10 requests per minute

[Addressing the community about changes to our API](https://old.reddit.com/r/reddit/comments/145bram/addressing_the_community_about_changes_to_our_api/)
> Effective July 1, 2023, the rate limits to use the Data API free of charge are:
> 100 queries per minute per OAuth client id if you are using OAuth authentication and 10 queries per minute if you are not using OAuth authentication.
