### ISSUE TITLE
BUG: if there are multiple results displayed as tabs, they all have the same number of upvotes 

### ISSUE THREAD

**Issue by sdas-tech** [z0ccc/voat-extension#41]
![image](https://github.com/z0ccc/voat-extension/assets/1049519/e8c0b6e0-5ac9-402a-915d-bb52c642ece0)
![image](https://github.com/z0ccc/voat-extension/assets/1049519/3409f6b8-a911-4600-8d63-7712dfb19364)
![image](https://github.com/z0ccc/voat-extension/assets/1049519/f091f555-6e63-4331-ad96-65e2008e9fa6)

The extension shows 988 for all, but these links actually have 988, 212, and 156 upvotes respectively.

Happens on all pages that have multiple reddit posts to it, not just youtube.

**Comment by z0ccc** [comment]
Will be fixed in next release. Thanks
